# -*- coding: utf-8 -*-
"""02_exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d6nBo_yuDTHvnCNVwAOvfPZCfh5YQ94a

# 演習
チャットボットの設定を、Streamlit Community Cloudの「Secrets」に保存しましょう。

## ライブラリのインストール
（※注: このノートブック内でこれらのライブラリを使うことは無いので、インストールは必要ありません。）
"""

# !pip install streamlit==1.20.0 --quiet
# !pip install openai

# import streamlit as st
# import openai

"""## チャットボットのコード
以下のコードの`st.secrets.AppSettings.chatbot_setting`で「system」の設定ができるように、Streamlit Community Cloudの「Secrets」に追記を行いましょう。  
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import openai
# 
# # Streamlit Community Cloudの「Secrets」からOpenAI API keyを取得
# openai.api_key = st.secrets.OpenAIAPI.openai_api_key
# 
# # st.session_stateを使いメッセージのやりとりを保存
# if "messages" not in st.session_state:
#     st.session_state["messages"] = [
#         {"role": "system", "content": st.secrets.AppSettings.chatbot_setting}
#         ]
# 
# # チャットボットとやりとりする関数
# def communicate():
#     messages = st.session_state["messages"]
# 
#     user_message = {"role": "user", "content": st.session_state["user_input"]}
#     messages.append(user_message)
# 
#     response = openai.ChatCompletion.create(
#         model="gpt-3.5-turbo",
#         messages=messages
#     )
# 
#     bot_message = response["choices"][0]["message"]
#     messages.append(bot_message)
# 
#     st.session_state["user_input"] = ""  # 入力欄を消去
# 
# 
# # ユーザーインターフェイスの構築
# st.title("My AI Assistant")
# st.write("ChatGPT APIを使ったチャットボットです。")
# 
# user_input = st.text_input("メッセージを入力してください。", key="user_input", on_change=communicate)
# 
# if st.session_state["messages"]:
#     messages = st.session_state["messages"]
# 
#     for message in reversed(messages[1:]):  # 直近のメッセージを上に
#         speaker = "🙂"
#         if message["role"]=="assistant":
#             speaker="🤖"
# 
#         st.write(speaker + ": " + message["content"])

"""## requirements.txtの作成"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit==1.20.0
# openai

"""以下の作成されたファイルをダウンロードして、新たなGitHubのレポジトリにアップしましょう。
* app.py
* requirements.txt
  
Streamlit Community Cloud上で動作を確認してください。

## 解答例
以下は解答例です。  
以下のような記述を「Secrets」に追記します。

[AppSettings]  
chatbot_setting = "あなたは優秀な英語教師です。何を聞かれても英語で答えてください。"
"""